parameters:
    bangpound_oembed.twig_extension.class: 'Bangpound\Sculpin\Bundle\OEmbedBundle\Twig\Extension\OEmbedExtension'

services:
    bangpound_oembed.twig_extension:
        class: '%bangpound_oembed.twig_extension.class%'
        arguments: [ %kernel.cache_dir% ]
        tags:
            - { name: twig.extension }
